Add meta tags
nyudlts/ultraviolet pull request #208
Opened 2024-11-26 15:10 UTC by zuchuandatou

- Add meta tags for Highwire Press on meta.html
- UI tests for meta tags

2024-11-26 20:24 UTC, ekate commented on tests/ui/test_meta_tags.py
@zuchuandatou, you do not need to add file to the draft record is this test

2024-11-26 20:28 UTC, ekate requested changes
@zuchuandatou, please change date on the Copyright statement to include current year.
Also, check my comment about adding file in the test record. i thin k we do not need it in that test

2024-11-26 20:41 UTC, zuchuandatou commented on tests/ui/test_meta_tags.py
Thanks for you info! Gonna give it a try without draft record

2024-11-26 20:43 UTC, ekate commented on tests/ui/test_meta_tags.py
You need draft record, but do not need to add file to it

2024-11-26 21:05 UTC, zuchuandatou commented on tests/ui/test_meta_tags.py
Yeah that's what I mean - used a metadata only record. Just pushed.

2024-12-03 17:42 UTC, ekate approved these changes

2024-12-03 17:44 UTC, ekate approved these changes

2024-12-03 17:44 UTC, merged